name: chat_bot
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  image_picker: ^0.6.7
  cached_network_image: ^2.2.0+1
  font_awesome_flutter: ^8.8.1
  provider: ^3.0.0
  cloud_firestore: ^0.12.9+5
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  percent_indicator: ^2.1.4
  http: ^0.12.1
  flutter_spinkit: "^2.1.0"
  audioplayers: ^0.15.1
  flutter_rating_bar: ^3.0.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
   - assets/images/default-user-placeholder.png
   - assets/images/avatar.jpg
   - assets/images/chatbot.png
   - assets/images/logo.jpg
   - assets/images/Bar01.png
   - assets/images/movie_placeholder.png
   - assets/images/Asset 01.png
   - assets/soundEffects/typing.mp3
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf